# -*- coding: utf-8 -*-
"""voice-chat-with-chatgpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-vSksoyOEi7zWK7E29d3hY5OZW2fo3D
"""

language = 'pt'

"""## Audio recording with Python and JS"""

# referência: https://gist.github.com/korakot/c21c3476c024ad6d56d5f48b0bca92be

from IPython.display import Audio, display, Javascript
from google.colab import output
from base64 import b64decode

RECORD = """
const sleep  = time => new Promise(resolve => setTimeout(resolve, time))
const b2text = blob => new Promise(resolve => {
  const reader = new FileReader()
  reader.onloadend = e => resolve(e.srcElement.result)
  reader.readAsDataURL(blob)
})
var record = time => new Promise(async resolve => {
  stream = await navigator.mediaDevices.getUserMedia({ audio: true })
  recorder = new MediaRecorder(stream)
  chunks = []
  recorder.ondataavailable = e => chunks.push(e.data)
  recorder.start()
  await sleep(time)
  recorder.onstop = async ()=>{
    blob = new Blob(chunks)
    text = await b2text(blob)
    resolve(text)
  }
  recorder.stop()
})
"""

def record(sec=5):
    display(Javascript(RECORD))
    js_result = output.eval_js('record(%s)' % (sec * 1000))
    audio = b64decode(js_result.split(',')[1])
    file_name = 'request_audio.wav'
    with open(file_name, 'wb') as f:
        f.write(audio)
    return file_name

print('Gravando!')
record_file = record()
display(Audio(record_file, autoplay=True))

"""## Speech recognition with Whisper (OpenAI)"""

!pip install git+https://github.com/openai/whisper.git -q

import whisper

model = whisper.load_model("small")
result = model.transcribe(record_file, fp16=False, language=language)
transcription = result["text"]
print(transcription)

"""## Integrating with ChatGPT"""

!pip install openai
!pip install --upgrade openai

from openai import OpenAI

client = OpenAI(api_key="YOUR_KEY_HERE")

response = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[{
        "role": "user",
        "content": transcription
        }]
)

chatgpt_response = response.choices[0].message.content
print(chatgpt_response)

"""## Synthesizing ChatGPT's answer into audio with gTTS"""

!pip install gTTS

from gtts import gTTS

gtts_object = gTTS(text=chatgpt_response, language=language, slow=False)
response_audio = "response_audio.wav"
gtts_object.save(response_audio)
display(Audio(response_audio, autoplay=True))